apiVersion: v2

name: observability-stack
description: An all-in-one observability stack for Kubernetes, integrating Grafana, Prometheus, Loki, Tempo, Promtail, and the Kubernetes Dashboard.

version: 0.0.7
appVersion: 0.0.7

dependencies:
  - name: kube-prometheus-stack
    version: 48.2.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus
  - name: loki
    version: 5.10.0
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: 1.3.1
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.11.9
    repository: https://grafana.github.io/helm-charts
  - name: kubernetes-dashboard
    version: 6.0.8
    repository: https://kubernetes.github.io/dashboard/
    alias: dashboard

home: https://grafana.com/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/observability-stack/observability-stack_icon_2.png
sources:
  - https://github.com/grafana/grafana
  - https://github.com/grafana/loki
  - https://github.com/grafana/tempo
  - https://github.com/prometheus/prometheus
  - https://github.com/kubernetes/dashboard
keywords:
  - Observability
  - Metrics
  - Logging
  - Alerting
annotations:
  displayName: Observability Stack
  category: Developer Tools
  licenses: Apache-2.0
