apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  authentik: {{ .Values.authentik | toYaml | b64enc | quote }}
type: Opaque
