apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab.fullname" . }}-auth
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
data:
  authentik: >-
    {{ default "" .Values.runnerRegistrationToken | b64enc | quote }}
type: Opaque
