ingress:
  enabled: true

  annotations:
    {{- if .Emporium.Annotations }}
    {{- toYaml .Emporium.Annotations | nindent 4 }}
    {{- end }}
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: {{ .Emporium.Integrations.DNS.Hostname }}
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: {{ .Emporium.Name }}-tls
      hosts:
        - {{ .Emporium.Integrations.DNS.Hostname }}


## @userSupplied CacheEnabled
## @label Enable Cache Directory
## @type boolean
## @description Use a caching disk for the filebrowser. Default is false.
## @optional

## @userSupplied CacheSize
## @label Cache Directory Size
## @type byteSize
## @description Size for cache directory. Default is 10Gi. Only relevant if CacheEnabled is true.
## @optional
storage:
  workdir:
    enabled: {{ default false .Emporium.UserSupplied.CacheEnabled }}
    storageClass: ""
    existingClaim: ""
    accessMode: ReadWriteOnce
    size: {{ default "10Gi" .Emporium.UserSupplied.StorageSize }}

  data:
    enabled: true
    existingClaim: "{{ .Emporium.Integrations.Storage.Claims.Data.Name }}"
