image:
  repository: emporium-apps.docker.pkg.emporium.rocks/vscode
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

password:

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi

ingress:
  enabled: false
  ingressClassName: "nginx"
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

docker:
  repository: docker
  pullPolicy: Always
  tag: 23.0.1-dind