## @userSupplied StorageSize
## @label Storage Size
## @type string
## @description Size of the attached storage volume (e.g. 20Gi or 900Mi). Default is 8Gi.
## @optional

ingress:
  enabled: true

  annotations:
    {{- if .Emporium.Annotations }}
    {{- toYaml .Emporium.Annotations | nindent 4 }}
    {{- end }}
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: {{ .Emporium.Integrations.DNS.Hostname }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: {{ .Emporium.Name }}-tls
      hosts:
        - {{ .Emporium.Integrations.DNS.Hostname }}

persistence:
  enabled: true
  size: {{ default "8Gi" .Emporium.UserSupplied.StorageSize }}

## @userSupplied NvidiaEnabled
## @label use NVidia CPU for Video Transcoding
## @type bool
## @description Your streaming setup benefits heavily when you can transcode stuff on your GPU
## @optional
app:
  baseurl: {{ .Emporium.Integrations.DNS.Hostname }}
  nvidiaEnabled: {{ default false .Emporium.UserSupplied.NvidiaEnabled }}