## @userSupplied StorageSize
## @label Storage Size
## @type string
## @description Size of the storage volume (e.g. 20Gi or 900Mi). Default is 8Gi.
## @optional

## @userSupplied Username
## @label Admin Username
## @type string
## @description Username of the admin user

## @userSupplied Password
## @label Admin Password
## @type string
## @description Must be at least 10 characters long

## @userSupplied Email
## @label Admin Email
## @type string
## @description Email of the admin user, this is used to sign in.

## @userSupplied Title
## @label Blog Title
## @type string
## @description The title of your Blog. (You can change this later)
ghost:
  ghostUsername: "{{ .Emporium.UserSupplied.Username }}"
  ghostPassword: "{{ .Emporium.UserSupplied.Password }}"
  ghostEmail: "{{ .Emporium.UserSupplied.Email }}"
  ghostBlogTitle: "{{ .Emporium.UserSupplied.Title }}"
  ghostEnableHttps: true

  ghostHost: {{ .Emporium.Integrations.DNS.Hostname }}

  service:
    type: ClusterIP

  ingress:
    enabled: true

    pathType: Prefix

    annotations:
      {{- if .Emporium.Annotations }}
      {{- toYaml .Emporium.Annotations | nindent 6 }}
      {{- end }}
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      kubernetes.io/tls-acme: "true"

    hostname: {{ .Emporium.Integrations.DNS.Hostname }}
    tls: true

  persistence:
    size: {{ default "8Gi" .Emporium.UserSupplied.StorageSize }}

  mysql:
    auth:
      existingSecret: {{ printf "%s-mysql" .Emporium.Name }}
