## @userSupplied ArtifactsPersistenceSize
## @label Artifacts Persistence Size
## @type string
## @description Size of the local Artifacts volume
## @optional

## @userSupplied ArtifactsPersistenceStorageClass
## @label Artifacts Persistence StorageClass
## @type string
## @description The StorageClass to use for the Artifacts volume
## @optional

## @userSupplied PostgresqlPersistenceSize
## @label Postgresql Persistence Size
## @type string
## @description Size of the local Postgresql volume
## @optional

## @userSupplied PostgresqlPersistenceStorageClass
## @label Postgresql Persistence StorageClass
## @type string
## @description The StorageClass to use for the Postgresql volume
## @optional

## @userSupplied PostgresqlPassword
## @label Postgresql Password
## @type string
## @description The database password to use
artifacts:
  auth:
    oidc:
      clientId: {{ .Emporium.OpenIDConnect.ClientID }}
      issuer: {{ .Emporium.OpenIDConnect.Issuer }}
  baseUrl: https://{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
  database:
    url: postgresql://postgres:{{ .Emporium.UserSupplied.PostgresqlPassword }}@{{ .Emporium.Name }}-postgresql:5432/artifacts
  image:
    pullPolicy: Always
    repository: monostream/artifacts
  ingress:
    annotations:
      {{- if .Emporium.Annotations }}
      {{- toYaml .Emporium.Annotations | nindent 6 }}
      {{- end }}
      emporium.build/auth-disabled: "true"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    enabled: true
    hosts:
    - host: {{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
      paths:
      - path: /
        pathType: Prefix
    - host: api.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
      paths:
      - path: /
        pathType: Prefix
    - host: '*.docker.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      paths:
      - path: /
        pathType: Prefix
    - host: '*.helm.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      paths:
      - path: /
        pathType: Prefix
    - host: '*.maven.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      paths:
      - path: /
        pathType: Prefix
    - host: '*.nuget.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      paths:
      - path: /
        pathType: Prefix
    - host: '*.npm.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      paths:
      - path: /
        pathType: Prefix
    ingressClassName: nginx
    tls:
    - hosts:
      - {{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
      - api.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
      - '*.docker.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      - '*.helm.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      - '*.maven.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      - '*.nuget.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      - '*.npm.{{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}'
      secretName: artifacts-tls
  persistence:
    enabled: true
    {{- if .Emporium.UserSupplied.ArtifactsPersistenceSize }}
    size: {{ .Emporium.UserSupplied.ArtifactsPersistenceSize }}Gi
    {{- end }}
    {{- if .Emporium.UserSupplied.ArtifactsPersistenceStorageClass }}
    storageClass: {{ .Emporium.UserSupplied.ArtifactsPersistenceStorageClass }}
    {{- end }}
  serviceAccount:
    create: true
    name: artifacts
  storage:
    filesystem:
      path: /data

postgresql:
  auth:
    database: artifacts
    postgresPassword: {{ .Emporium.UserSupplied.PostgresqlPassword }}
  primary:
    persistence:
      enabled: true
      {{- if .Emporium.UserSupplied.PostgresqlPersistenceSize }}
      size: {{ .Emporium.UserSupplied.PostgresqlPersistenceSize }}Gi
      {{- end }}
      {{- if .Emporium.UserSupplied.PostgresqlPersistenceStorageClass }}
      storageClass: {{ .Emporium.UserSupplied.PostgresqlPersistenceStorageClass }}
      {{- end }}