affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
drawio:
  baseUrl: null
  cacheDomain: null
  city: null
  cloudConvertApiKey: null
  config: null
  countryCode: null
  cspHeader: null
  gitlabId: null
  gitlabSecret: null
  gitlabUrl: null
  googleAppId: null
  googleClientId: null
  googleClientSecret: null
  googleViewerAppId: null
  googleViewerClientId: null
  googleViewerClientSecret: null
  iotCertPem: null
  iotEndpoint: null
  iotPrivateKey: null
  iotRootCa: null
  lightboxUrl: null
  memcachedEndpoint: null
  msGraphClientId: null
  msGraphClientSecret: null
  msGraphTenantId: null
  mxPusherEndpoint: null
  organisation: null
  organisationUnit: null
  publicDns: domain.com
  state: null
  viewerUrl: null
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: jgraph/drawio
  tag: 23.0.0
imagePullSecrets: []
ingress:
  annotations: {}
  className: ""
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ""
tolerations: []
