## @userSupplied ArtifactsPersistenceSize
## @label Artifacts Persistence Size
## @type string
## @description Size of the local Artifacts volume
## @optional

## @userSupplied ArtifactsPersistenceStorageClass
## @label Artifacts Persistence StorageClass
## @type string
## @description The StorageClass to use for the Artifacts volume
## @optional

## @userSupplied PostgresqlPersistenceSize
## @label Postgresql Persistence Size
## @type string
## @description Size of the local Postgresql volume
## @optional

## @userSupplied PostgresqlPersistenceStorageClass
## @label Postgresql Persistence StorageClass
## @type string
## @description The StorageClass to use for the Postgresql volume
## @optional

## @userSupplied PostgresqlPassword
## @label Postgresql Password
## @type string
## @description The database password to use (if left empty SQLite will be used)
## @optional

## @userSupplied EnablePublicRead
## @label Enable public read
## @type boolean
## @description Enable anonymous read access for repositories set to public
## @optional

{{- if .Emporium.UserSupplied.PostgresqlPassword }}
global:
  postgresql:
    enabled: true
{{- end }}
artifacts:
  auth:
    oidc:
      clientId: {{ .Emporium.Integrations.OIDC.ClientID }}
      issuer: {{ .Emporium.Integrations.OIDC.Issuer }}
    {{- if .Emporium.UserSupplied.EnablePublicRead }}
    enablePublicRead: true
    {{- end }}
  hosts:
    domain: {{ .Emporium.Integrations.DNS.Hostname }}
    https: true
  {{- if .Emporium.UserSupplied.PostgresqlPassword }}
  database:
    url: postgresql://postgres:{{ .Emporium.UserSupplied.PostgresqlPassword }}@{{ .Emporium.Name }}-postgresql:5432/artifacts
  {{- end }}
  image:
    pullPolicy: Always
    repository: monostream.docker.pkg.emporium.rocks/artifacts
  ingress:
    annotations:
      {{- if .Emporium.Annotations }}
      {{- toYaml .Emporium.Annotations | nindent 6 }}
      {{- end }}
      kubernetes.io/tls-acme: "true"
    enabled: true
  persistence:
    enabled: true
    {{- if .Emporium.UserSupplied.ArtifactsPersistenceSize }}
    size: {{ .Emporium.UserSupplied.ArtifactsPersistenceSize }}
    {{- end }}
    {{- if .Emporium.UserSupplied.ArtifactsPersistenceStorageClass }}
    storageClass: {{ .Emporium.UserSupplied.ArtifactsPersistenceStorageClass }}
    {{- end }}
  serviceAccount:
    create: true
    name: artifacts
  storage:
    filesystem:
      path: /data

{{- if .Emporium.UserSupplied.PostgresqlPassword }}
postgresql:
  auth:
    database: artifacts
    postgresPassword: {{ .Emporium.UserSupplied.PostgresqlPassword }}
  primary:
    persistence:
      enabled: true
      {{- if .Emporium.UserSupplied.PostgresqlPersistenceSize }}
      size: {{ .Emporium.UserSupplied.PostgresqlPersistenceSize }}
      {{- end }}
      {{- if .Emporium.UserSupplied.PostgresqlPersistenceStorageClass }}
      storageClass: {{ .Emporium.UserSupplied.PostgresqlPersistenceStorageClass }}
      {{- end }}
  {{- end }}