## @userSupplied AppName
## @label AppName
## @type string
## @description Add a fancy name to your pastepass
## @optional

storage:
  workdir:
    enabled: true
    existingClaim: "{{ .Emporium.Integrations.Storage.Claims.Workspace.Name }}"

app:
  name: {{ default "Pastepass" .Emporium.UserSupplied.AppName }}

ingress:
  enabled: true
  annotations:
    {{- if .Emporium.Annotations }}
    {{- toYaml .Emporium.Annotations | nindent 4 }}
    {{- end }}
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: {{ .Emporium.Integrations.DNS.Hostname }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: {{ .Emporium.Name }}-tls
      hosts:
        - {{ .Emporium.Integrations.DNS.Hostname }}