wiki:
  ingress:
    enabled: true
    annotations:
      glass.monostream.com/enabled: "true"
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: {{ .AppStore.Name }}-tls
        hosts:
          - {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}

# https://docs.requarks.io/install/kubernetes
# kubectl delete pvc/data-wiki-postgresql-0
