apiVersion: v2
name: uptime-kuma
description: Uptime Kuma is an easy-to-use self-hosted monitoring tool.
type: application
version: 0.0.21
appVersion: "2.0.0-beta.0"
home: https://uptime.kuma.pet/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/uptime-kuma/uptime-kuma_icon_2.svg
sources:
  - https://github.com/louislam/uptime-kuma
keywords:
  - Monitoring
  - Uptime
  - Performance
  - DevOps
annotations:
  displayName: Uptime Kuma
  licenses: MIT
  category: Monitoring
