annotations:
  category: Developer Tools
  displayName: GitLab
  licenses: MIT
  oidcRedirectPaths: /users/auth/openid_connect/callback
apiVersion: v2
appVersion: 0.0.8
dependencies:
- name: gitlab
  repository: https://charts.gitlab.io/
  version: 7.7.2
description: A single plattform to experience and share frustration with other developers
home: https://gitlab.com/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/gitlab/gitlab_icon_2.svg
keywords:
- Collaboration
- Coding
- Git
- CI/CD
- Issue Tracking
name: gitlab
sources:
- https://docs.gitlab.com/charts/installation/
type: application
version: 16.5.1
