apiVersion: v2

name: drawio
description: Online diagram software for making flowcharts, process diagrams, org charts, UML, ER and network diagrams.

type: application
version: 0.1.3
appVersion: "21.3.3"

home: https://www.drawio.com/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/drawio/drawio_icon_2.png
sources:
  - https://github.com/jgraph/drawio
  - https://github.com/jgraph/docker-drawio
maintainers:
  - name: JGraph Ltd and draw.io AG
    url: https://github.com/jgraph/drawio
keywords:
  - Diagrams

annotations:
  category: Utilities
  licenses: Apache-2.0
