ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: drawio.bubu.hair
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: bubuhair-tls
     hosts:
       - drawio.bubu.hair