apiVersion: v1
kind: Secret
metadata:
  name: "penpot-secret"
type: Opaque
data:
  postgresql-username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  smtp-username: {{ .Values.smpt.password | b64enc | quote }}
  smtp-password: {{ .Values.smpt.username | b64enc | quote }}