## @userSupplied Username
## @label Admin Username
## @type string
## @description Username of the admin user

## @userSupplied Password
## @label Admin Password
## @type string
## @description Must be at least 10 characters long

## @userSupplied Email
## @label Admin Email
## @type string
## @description Email of the admin user, this is used to sign in.

## @userSupplied Title
## @label Blog Title
## @type string
## @description The title of your Blog. (You can change this later)
ghost:
  ghostUsername: {{ .AppStore.UserSupplied.Username }}
  ghostPassword: {{ .AppStore.UserSupplied.Password }}
  ghostEmail: {{ .AppStore.UserSupplied.Email }}
  ghostBlogTitle: {{ .AppStore.UserSupplied.Title }}
  ghostEnableHttps: true

  ghostHost: {{ .AppStore.Name }}.{{ .AppStore.DNSZone }}

  service:
    type: ClusterIP

  ingress:
    enabled: true

    pathType: Prefix

    annotations:
      glass.monostream.com/enabled: "true"
      kubernetes.io/tls-acme: "true"

    hostname: {{ .AppStore.Name }}.{{ .AppStore.DNSZone }}
    tls: true
