# {{- if .Values.secret }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ include "n8n.fullname" . }}-emporium
#   labels:
#     {{- include "n8n.labels" . | nindent 4 }}
#   annotation:
#     helm.sh/resource-policy: keep
# data:
#   secret.json: |
#     {
#       "database": {
#         "postgresdb": {
#           "password": {{ randAlphaNum 16 | b64enc | quote }}
#         }
#       }

# {{- end }}
