apiVersion: v2

name: penpot
description: The Open-Source design & prototyping platform

type: application
version: 1.0.12
appVersion: 1.16.0-beta

home: https://github.com/codechem/helm/tree/main/charts/penpot
icon: https://avatars.githubusercontent.com/u/30179644?s=200&v=4
sources:
- https://github.com/penpot/penpot
maintainers:
- name: codechem
  url: https://codechem.com
keywords:
- design
- UI

dependencies:
- condition: global.postgresqlEnabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.x.x
- condition: global.redisEnabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.x.x

annotations:
  category: design
  licenses: MPL-2.0 license

