## @userSupplied APISecretKey
## @label API Secret Key
## @type string
## @description Generate with `openssl rand -hex 16` for example

## @userSupplied SMTPDefaultFrom
## @label SMTP Default From
## @type string
## @description The SMTP default email to send from

## @userSupplied SMTPDefaultReplyTo
## @label SMTP Default Reply To
## @type string
## @description The SMTP default email to reply to

## @userSupplied SMTPHost
## @label SMTP Host
## @type string
## @description The SMTP host to use

## @userSupplied SMTPPort
## @label SMTP Port
## @type string
## @description The SMTP host port to use

## @userSupplied SMTPUsername
## @label SMTP Username
## @type string
## @description The SMTP username to use

## @userSupplied SMTPPassword
## @label SMTP Password
## @type string
## @description The SMTP password to use

## @userSupplied PostgresPassword
## @label Postgres Password
## @type string
## @description The database password to use
global:
  postgresqlEnabled: true
  redisEnabled: true

frontend:
  ingress:
    enabled: true

    annotations:
      glass.monostream.com/enabled: "true"
      kubernetes.io/tls-acme: "true"

    hosts:
      - host: {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}

    tls:
      - secretName: {{ .AppStore.Name }}-tls
        hosts:
          - {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}

persistence:
  enabled: true
  size: 50Gi

config:
  publicURI: {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}
  flags: "enable-registration enable-login enable-smtp disable-demo-users disable-demo-warning"
  apiSecretKey: "{{ .AppStore.UserSupplied.APISecretKey }}"

  postgresql:
    host: {{ .AppStore.Name }}-postgresql
    port: 5432
    database: penpot
    existingSecret: "penpot-secret"
    secretKeys:
      usernameKey: "postgresql-username"
      passwordKey: "postgresql-password"

  redis:
    host: {{ .AppStore.Name }}-redis-headless
    port: 6379
    database: "0"

  smtp:
    enabled: true
    defaultFrom: "{{ .AppStore.UserSupplied.SMTPDefaultFrom }}"
    defaultReplyTo: "{{ .AppStore.UserSupplied.SMTPDefaultReplyTo }}"
    host: "{{ .AppStore.UserSupplied.SMTPHost }}"
    port: "{{ .AppStore.UserSupplied.SMTPPort }}"
    tls: true
    existingSecret: "penpot-secret"
    secretKeys:
      usernameKey: "smtp-username"
      passwordKey: "smtp-password"

smtp:
  username: "{{ .AppStore.UserSupplied.SMTPUsername }}"
  password: "{{ .AppStore.UserSupplied.SMTPPassword }}"

postgresql:
  auth:
    username: admin
    password: "{{ .AppStore.UserSupplied.PostgresPassword }}"
    database: penpot

  # providers:
    # oidc:
    #   enabled: false
    #   baseURI: ""
    #   clientID: ""
    #   clientSecret: ""
    #   authURI: ""
    #   tokenURI: ""
    #   userURI: ""
    #   roles: "role1 role2"
    #   rolesAttribute: ""
    #   scopes: "scope1 scope2"
    #   nameAttribute: ""
    #   emailAttribute: ""
