## @userSupplied APISecretKey
## @label API Secret Key
## @type string
## @description API Secret Key

## @userSupplied SMTPDefaultFrom
## @label SMTP Default From
## @type string
## @description SMTP Default From

## @userSupplied SMTPDefaultReplyTo
## @label SMTP Default Reply To
## @type string
## @description SMTP Default Reply To

## @userSupplied SMTPHost
## @label SMTP Host
## @type string
## @description SMTP Host

## @userSupplied SMTPPort
## @label SMTP Port
## @type string
## @description SMTP Port

## @userSupplied SMTPUsername
## @label SMTP Username
## @type string
## @description SMTP Username

## @userSupplied SMTPPassword
## @label SMTP Password
## @type string
## @description SMTP Password

## @userSupplied PostgresPassword
## @label Postgres Password
## @type string
## @description Postgres Password
global:
  postgresqlEnabled: true
  redisEnabled: true

frontend:
  ingress:
    enabled: true

    annotations:
      glass.monostream.com/enabled: "true"
      kubernetes.io/tls-acme: "true"

    hosts:
      - host: {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}

    tls:
      - secretName: {{ .AppStore.Name }}-tls
        hosts:
          - {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}

persistence:
  enabled: true
  size: 50Gi

config:
  publicURI: {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}
  flags: "enable-registration enable-login disable-demo-users disable-demo-warning"
  apiSecretKey: {{ .AppStore.UserSupplied.APISecretKey }} #quote

  postgresql:
    host: {{ .AppStore.Name }}-postgresql
    port: 5432
    database: penpot
    existingSecret: "penpot-secret"
    secretKeys:
      usernameKey: "postgresql-username"
      passwordKey: "postgresql-password"

  redis:
    host: {{ .AppStore.Name }}-redis-headless
    port: 6379
    database: "0"

  smtp:
    enabled: true
    defaultFrom: {{ .AppStore.UserSupplied.SMTPDefaultFrom }} #quote
    defaultReplyTo: {{ .AppStore.UserSupplied.SMTPDefaultReplyTo }} #quote
    host: {{ .AppStore.UserSupplied.SMTPHost }}
    port: {{ .AppStore.UserSupplied.SMTPPort }}
    tls: true
    existingSecret: "penpot-secret"
    secretKeys:
      usernameKey: "smtp-username"
      passwordKey: "smtp-password"

smtp:
  username: {{ .AppStore.UserSupplied.SMTPUsername }} #quote
  password: {{ .AppStore.UserSupplied.SMTPPassword }} #quote

postgresql:
  auth:
    username: admin
    password: {{ .AppStore.UserSupplied.PostgresPassword }} #quote
    database: penpot

  # providers:
    # oidc:
    #   enabled: false
    #   baseURI: ""
    #   clientID: ""
    #   clientSecret: ""
    #   authURI: ""
    #   tokenURI: ""
    #   userURI: ""
    #   roles: "role1 role2"
    #   rolesAttribute: ""
    #   scopes: "scope1 scope2"
    #   nameAttribute: ""
    #   emailAttribute: ""
