global:
  postgresqlEnabled: true
  redisEnabled: true

frontend:
  ingress:
    enabled: true

    annotations:
      glass.monostream.com/enabled: "true"
      kubernetes.io/tls-acme: "true"

    hosts:
      - host: {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}

    tls:
      - secretName: {{ .AppStore.Name }}-tls
        hosts:
          - {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}

persistence:
  enabled: true
  size: 50Gi

config:
  publicURI: {{ .AppStore.Subdomain }}.{{ .AppStore.DNSZone }}
  flags: "enable-registration enable-login disable-demo-users disable-demo-warning"
  apiSecretKey: {{ quote .AppStore.UserSupplied.APISecretKey }}

  postgresql:
    host: {{ .AppStore.Name }}-postgresql
    port: 5432
    database: penpot
    existingSecret: "penpot-secret"
    secretKeys:
      usernameKey: "postgresql-username"
      passwordKey: "postgresql-password"

  redis:
    host: {{ .AppStore.Name }}-redis-headless
    port: 6379
    database: "0"

  smtp:
    enabled: true
    defaultFrom: {{ quote .AppStore.UserSupplied.SMTPDefaultFrom }}
    defaultReplyTo: {{ quote .AppStore.UserSupplied.SMTPDefaultReplyTo }}
    host: {{ .AppStore.UserSupplied.SMTPHost }}
    port: {{ .AppStore.UserSupplied.SMTPPort }}
    tls: true
    existingSecret: "penpot-secret"
    secretKeys:
      usernameKey: "smtp-username"
      passwordKey: "smtp-password"

smtp:
  username: {{ quote .AppStore.UserSupplied.SMTPUsername }}
  password: {{ quote .AppStore.UserSupplied.SMTPPassword }}

postgresql:
  auth:
    username: admin
    password: {{ quote .AppStore.UserSupplied.PostgresPassword }}
    database: penpot

  # providers:
    # oidc:
    #   enabled: false
    #   baseURI: ""
    #   clientID: ""
    #   clientSecret: ""
    #   authURI: ""
    #   tokenURI: ""
    #   userURI: ""
    #   roles: "role1 role2"
    #   rolesAttribute: ""
    #   scopes: "scope1 scope2"
    #   nameAttribute: ""
    #   emailAttribute: ""
