apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl (.Values.app.config | toYaml) . | nindent 4 }}
