apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-job-sa
  labels:
    {{- include "chart.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.fullname" . }}-job-role
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "secrets"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-job-rolebinding
  labels:
    {{- include "chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "chart.fullname" . }}-job-sa
roleRef:
  kind: Role
  name: {{ include "chart.fullname" . }}-job-role
  apiGroup: rbac.authorization.k8s.io
