{{- $secretName := printf "%s-root-api-key" (include "chart.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
    {{- with .Values.secretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  ROOT_API_KEY: {{ if and $existingSecret $existingSecret.data (hasKey $existingSecret.data "ROOT_API_KEY") }}{{ index $existingSecret.data "ROOT_API_KEY" }}{{ else }}{{ "" | b64enc }}{{ end }}
  COOKIE_SECRET: "{{- include "chart.secretValue" (dict "secretName" $secretName "key" "COOKIE_SECRET" "defaultValue" (randAlphaNum 36) "Release" .Release) }}"
