apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.web.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
