apiVersion: v2
name: observability-stack
description: An all-in-one observability stack for Kubernetes, integrating Grafana, Prometheus, Loki, Tempo, Promtail, and Pyroscope.
version: 0.0.16
appVersion: 0.0.1
dependencies:
    - name: kube-prometheus-stack
      version: 54.2.2
      repository: https://prometheus-community.github.io/helm-charts
      alias: prometheus
    - name: loki
      version: 5.38.0
      repository: https://grafana.github.io/helm-charts
    - name: tempo
      version: 1.7.1
      repository: https://grafana.github.io/helm-charts
    - name: promtail
      version: 6.15.3
      repository: https://grafana.github.io/helm-charts
    - name: pyroscope
      version: 1.3.0
      repository: https://grafana.github.io/helm-charts
home: https://grafana.com/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/observability-stack/observability-stack_icon_2.svg
sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/loki
    - https://github.com/grafana/tempo
    - https://github.com/grafana/pyroscope
    - https://github.com/prometheus/prometheus
keywords:
    - Observability
    - Metrics
    - Logging
    - Alerting
annotations:
    displayName: Observability Stack
    category: Developer Tools
    licenses: Apache-2.0
