ingress:
  enabled: true

  annotations:
    {{- if .Emporium.Annotations }}
    {{- toYaml .Emporium.Annotations | nindent 4 }}
    {{- end }}
    kubernetes.io/tls-acme: "true"

  host: {{ .Emporium.Integrations.DNS.Hostname }}
  tls:
    secretName: plane-tls
    host: {{ .Emporium.Integrations.DNS.Hostname }}
