app:
  url: "https://{{ .Emporium.Integrations.DNS.Hostname }}"
  oidc:
    issuer: "{{ .Emporium.Integrations.OIDC.Issuer }}"
    clientId: "{{ .Emporium.Integrations.OIDC.ClientID }}"
    clientSecret: "{{ .Emporium.Integrations.OIDC.ClientSecret }}"


ingress:
  enabled: true
  annotations:
    {{- if .Emporium.Annotations }}
    {{- toYaml .Emporium.Annotations | nindent 4 }}
    {{- end }}
    kubernetes.io/tls-acme: "true"
    emporium.build/auth-skip-paths: '/api/*,/#/*'
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  hosts:
    - host: {{ .Emporium.Integrations.DNS.Hostname }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: {{ .Emporium.Name }}-tls
      hosts:
        - {{ .Emporium.Integrations.DNS.Hostname }}

postgresql:
  fullnameOverride: "{{ .Emporium.Name }}-postgresql"

  auth:
    existingSecret: "{{ .Emporium.Name }}-postgresql"


minio:
  fullnameOverride: "{{ .Emporium.Name }}-minio"

  auth:
    existingSecret: "{{ .Emporium.Name }}-minio"

  apiIngress:
    enabled: true

    hostname: "minio-{{ .Emporium.Integrations.DNS.Hostname }}"

    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 16m

    extraTls:
      - hosts:
          - "minio-{{ .Emporium.Integrations.DNS.Hostname }}"
        secretName: "{{ .Emporium.Name }}-minio-tls"
