apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebrowser
data:
  .filebrowser.json: {{ tpl (.Values.config | toYaml) . | nindent 4 }}