{{- if and .Values.cache.enabled (not .Values.cache.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}-cache
{{- with .Values.cache.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- if .Values.cache.labels }}
{{ toYaml .Values.cache.labels | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.cache.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.cache.size | quote }}
{{- if .Values.cache.storageClass }}
{{- if (eq "-" .Values.cache.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.cache.storageClass }}"
{{- end }}
{{- end }}
{{- end }}