## @userSupplied OpenaiApiKey
## @label OpenAI API key
## @type string
## @description API Key to authenticate with OpenAI
## @optional

## @userSupplied OllamaEnabled
## @label Enable Ollama
## @type boolean
## @optional

## @userSupplied EnableGPU
## @label Enable GPU
## @type bool
## @description Enable GPU for Ollama
## @optional

## @userSupplied GPUType
## @label GPU Type
## @type string
## @description GPU Type can be either nvidia or amd
## @optional

## @userSupplied RuntimeClassName
## @label Runtime class name
## @type string
## @description Name of the Runtime class which is capable of running GPU enabled workload
## @optional

open-webui:
  extraEnvVars:
    - name: OPENAI_API_KEY
      value: {{ .Emporium.UserSupplied.OpenaiApiKey }}
    - name: OAUTH_CLIENT_ID
      value: {{ .Emporium.Integrations.OIDC.ClientID }}
    - name: OAUTH_CLIENT_SECRET
      value: {{ .Emporium.Integrations.OIDC.ClientSecret }}
    - name: OPENID_PROVIDER_URL
      value: {{ .Emporium.Integrations.OIDC.ConfigurationEndpoint }}
    - name: OAUTH_PROVIDER_NAME
      value: "Authentik"
    - name: OAUTH_SCOPES
      value: "openid email profile"
    - name: ENABLE_OAUTH_SIGNUP
      value: "true"

  ingress:
    enabled: true
    annotations:
      {{- if .Emporium.Annotations }}
      {{- toYaml .Emporium.Annotations | nindent 6 }}
      {{- end }}
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    host: {{ .Emporium.Integrations.DNS.Hostname }}
    tls: true

  persistence:
    enabled: true
    existingClaim: {{ .Emporium.Integrations.Storage.Claims.Data.Name }}

  ollama:
    enabled: {{ default false .Emporium.UserSupplied.OllamaEnabled }}
    ollama:
      gpu:
        enabled: {{ default false .Emporium.UserSupplied.EnableGPU }}
        type: {{ default "nvidia" .Emporium.UserSupplied.GPUType }}
        number: 1
      models:
        - llama3
    runtimeClassName: {{ .Emporium.UserSupplied.RuntimeClassName }}
    persistentVolume:
      enabled: true
      existingClaim: {{ .Emporium.Integrations.Storage.Claims.Ollama.Name }}

