nameOverride: ""

plausible:
  baseURL: ""
  disableRegistration: true
  logFailedLoginAttempts: true

  secret:
    create: false
    existingSecret: plausible

  postgresql:
    fullNameOverride: plausible-postgresql
    auth:
      existingSecret: plausible
      secretKeys:
        adminPasswordKey: "DATABASE_PASSWORD"
    primary:
      persistence:
        enabled: true
        size: 10Gi


  clickhouse:
    fullNameOverride: plausible-clickhouse
    auth:
      existingSecret: plausible
      existingSecretKey: "CLICKHOUSE_PASSWORD"
    persistence:
      enabled: true
      size: 10Gi
