apiVersion: v2
name: uptrace
description: Open Source Observability with Traces, Metrics, and Logs
type: application
version: 0.0.1
appVersion: "1.7.4"
home: https://uptrace.dev/
icon: https://raw.githubusercontent.com/monostream/emporium-catalog/main/assets/uptrace/uptrace_icon_2.svg
sources:
  - https://github.com/uptrace/helm-charts/
keywords:
  - Observability
  - Tracing
  - Logs
  - Metrics
  - Alerting
dependencies:
  - name: opentelemetry-operator
    version: 0.60.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: uptrace
    version: 1.7.4
    repository: https://charts.uptrace.dev
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami