## @userSupplied StorageSize
## @label Storage Size
## @type string
## @description Size of the storage volume (e.g. 20Gi or 900Mi). Default is 8Gi.
## @optional

n8n:
  ingress:
    enabled: true
    annotations:
      {{- if .Emporium.Annotations }}
      {{- toYaml .Emporium.Annotations | nindent 6 }}
      {{- end }}
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: {{ .Emporium.Integrations.DNS.Hostname }}
        paths:
          - /
    tls:
      - secretName: {{ .Emporium.Name }}-tls
        hosts:
          - {{ .Emporium.Integrations.DNS.Hostname }}

  persistence:
    enabled: true
    type: dynamic
    size: {{ default "8Gi" .Emporium.UserSupplied.StorageSize }}

