annotations:
  category: Developer Tools
  displayName: GitHub Actions Runner
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.7.0
dependencies:
- name: gha-runner-scale-set-controller
  repository: oci://ghcr.io/actions/actions-runner-controller-charts
  version: 0.8.1
- name: gha-runner-scale-set
  repository: oci://ghcr.io/actions/actions-runner-controller-charts
  version: 0.8.1
description: GitHub Actions Runner orchestrates and scales self-hosted runners for
  GitHub Actions
icon: https://avatars.githubusercontent.com/u/44036562?s=256&v=4
keywords:
- SelfHosted
- CI/CD
name: gha-runner
sources:
- https://github.com/actions/actions-runner-controller
version: 0.0.5
