{{- if .Values.nextcloud.postgresql.global.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nextcloud.postgresql.global.postgresql.auth.existingSecret }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  admin: {{ printf "admin" | b64enc | quote }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  postgres-password: {{ randAlphaNum 16 | b64enc | quote }}
type: Opaque
{{- end }}
