{{- if .Values.nextcloud.nextcloud.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nextcloud.nextcloud.existingSecret.secretName }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  nextcloud-username: {{ printf "admin" | b64enc | quote }}
  nextcloud-password: {{ randAlphaNum 16 | b64enc | quote }}
  nextcloud-token: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
