{{- if .Values.nextcloud.redis.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nextcloud.redis.auth.existingSecret }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  redis-password: {{ randAlphaNum 16 | b64enc | quote }}
type: Opaque
{{- end }}
