porter:
  server:
    url: https://{{ .Emporium.Integrations.DNS.Hostname }}

    additionalEnv:
      FEATURE_FLAG_CLIENT: database

  ingress:
    enabled: true

    annotations:
      {{- if .Emporium.Annotations }}
      {{- toYaml .Emporium.Annotations | nindent 6 }}
      {{- end }}
      kubernetes.io/tls-acme: "true"

    hosts:
      - host: {{ .Emporium.Integrations.DNS.Hostname }}
        paths:
          - /

    tls:
      - secretName: porter-cert-tls
        hosts:
          - {{ .Emporium.Integrations.DNS.Hostname }}