## @userSupplied RuntimeClassName
## @label Runtime class name
## @type string
## @description Name of the Runtime class which is capable of running GPU enabled workload

## @userSupplied StorageSize
## @label StorageSize
## @type byteSize
## @description The size of the storage volume
ollama:
  nameOverride: "ollama"
  fullnameOverride: "ollama"

  ollama:
    gpu:
      enabled: true
      number: 1
    defaultModel: "llama2"

  runtimeClassName: {{ .Emporium.UserSupplied.RuntimeClassName }}

  persistentVolume:
    enabled: true
    size: {{ .Emporium.UserSupplied.StorageSize }}

ollama-webui:
  ingress:
    enabled: true
    annotations:
      {{- if .Emporium.Annotations }}
      {{- toYaml .Emporium.Annotations | nindent 6 }}
      {{- end }}
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: {{ .Emporium.Integrations.DNS.Hostname }}
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: {{ .Emporium.Name }}-webui-tls
        hosts:
          - {{ .Emporium.Integrations.DNS.Hostname }}