{{- if not (and .Values.encryptionKey.secretName .Values.auth.cookie.hashKey.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifacts.fullname" . }}
  labels:
    {{- include "artifacts.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "artifacts.fullname" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- if empty .Values.encryptionKey.secretName }}
  {{- $encryptionKey := (get $secretData "encryption-key") | default (randAlphaNum 32 | b64enc | b64enc) }}
  encryption-key: {{ $encryptionKey | quote }}
  {{- end }}
  {{- if empty .Values.auth.cookie.hashKey.secretName }}
  {{- $cookieSigningKey := (get $secretData "cookie-signing-key") | default (randAlphaNum 64 | b64enc | b64enc) }}
  cookie-signing-key: {{ $cookieSigningKey | quote }}
  {{- end }}
{{- end }}