apiVersion: v2

name: chatbotui
description: An open source alternative ChatGPT UI.

type: application
version: 0.1.5
appVersion: "0.1.0"

home: https://www.chatbotui.com/
icon: https://raw.githubusercontent.com/monostream/test-charts/main/assets/chatbot-ui/chatbot-ui_icon_2.png
sources:
  - https://github.com/mckaywrigley/chatbot-ui
keywords:
  - ChatGPT
  - AI
maintainers:
  - name: Mckay Wrigley
    url: https://github.com/mckaywrigley

annotations:
  category: AI
  licenses: MIT
  gallery: |
    https://raw.githubusercontent.com/monostream/test-charts/main/assets/chatbot-ui/chatbot-ui_gallery_1.jpg
