## @userSupplied OpenAIAPIKey
## @label OpenAI API Key
## @type string
## @description OpenAI API Key
openai:
  apiKey: "{{ .Emporium.UserSupplied.OpenAIAPIKey }}"

image:
  tag: latest

ingress:
  enabled: true

  annotations:
    {{- if .Emporium.Annotations }}
    {{- toYaml .Emporium.Annotations | nindent 4 }}
    {{- end }}
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: {{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: {{ .Emporium.Name }}-tls
      hosts:
        - {{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
