## @userSupplied OpenAIAPIKey
## @label OpenAI API Key
## @type string
## @description OpenAI API Key
openai:
  apiKey: "{{ .Emporium.UserSupplied.OpenAIAPIKey }}"

## @userSupplied DefaultModel
## @label OpenAI Model
## @type string
## @description choose the model that is used (eg. gpt-4, gpt-3.5-turbo) see https://platform.openai.com/docs/models/how-we-use-your-data for more information
chatbotui:
  defaultModel: "{{ .Emporium.UserSupplied.DefaultModel }}"
  defaultSystemPrompt: "You are MonoGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."
  defaultTemperature: 1

image:
  tag: latest

ingress:
  enabled: true

  annotations:
    {{- if .Emporium.Annotations }}
    {{- toYaml .Emporium.Annotations | nindent 4 }}
    {{- end }}
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: {{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: {{ .Emporium.Name }}-tls
      hosts:
        - {{ .Emporium.Subdomain }}.{{ .Emporium.DNSZone }}
