openai:
  apiKey: {{ .AppStore.UserSupplied.OpenAIAPIKey }}

image:
  tag: latest

ingress:
  enabled: true

  annotations:
    glass.monostream.com/enabled: "true"
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: {{ .AppStore.Name }}.{{ .AppStore.DNSZone }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: {{ .AppStore.Name }}-tls
      hosts:
        - {{ .AppStore.Name }}.{{ .AppStore.DNSZone }}
