apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.adminUser) }}
  jenkins-username: {{ .Values.adminUser | b64enc | quote }}
  {{- else }}
  jenkins-username: admin
  {{- end }}
  {{- if not (empty .Values.adminPassword) }}
  jenkins-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  jenkins-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- if .Values.oidc }}
  jenkins-oidc-client-id: {{ .Values.oidc.clientId | default "" | b64enc | quote }}
  jenkins-oidc-client-secret: {{ .Values.oidc.clientSecret | default "" | b64enc | quote }}
  {{- end }}
  