apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}-api
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
  {{- with .Values.devcloud.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.devcloud.service.type }}
  ports:
    - port: {{ .Values.devcloud.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
