apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}-jnlp
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
  {{- with .Values.jnlp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.jnlp.service.type }}
  ports:
    - port: {{ .Values.jnlp.service.port }}
      targetPort: jnlp
      protocol: TCP
      name: jnlp
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
