apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  postgres-password: "{{- include "chart.secretValue" (dict "secretName" "postgresql" "key" "password" "defaultValue" (randAlphaNum 32) "Release" .Release) }}"
  password: "{{- include "chart.secretValue" (dict "secretName" "postgresql" "key" "password" "defaultValue" (randAlphaNum 32) "Release" .Release) }}"

