apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-minio
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
    {{- with .Values.secretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  root-user: {{ "lobe" | b64enc | quote }}
  root-password: {{ randAlphaNum 32 | b64enc | quote }}

