apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-keyvaults
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  keyvaultssecret: "{{- include "chart.secretValue" (dict "secretName" (print (include "chart.fullname" .) "-keyvaults") "key" "SECRET_KEY_BASE" "defaultValue" (randAlphaNum 32) "Release" .Release) }}"
