apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-nextauth-secret
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  NEXTAUTH_SECRET: "{{- include "chart.secretValue" (dict "secretName" (print (include "chart.fullname" .) "-nextauth-secret") "key" "NEXTAUTH_SECRET" "defaultValue" (randAlphaNum 36) "Release" .Release) }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-encryption-key
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  NEXT_PRIVATE_ENCRYPTION_KEY: "{{- include "chart.secretValue" (dict "secretName" (print (include "chart.fullname" .) "-encryption-key") "key" "NEXT_PRIVATE_ENCRYPTION_KEY" "defaultValue" (randAlphaNum 36) "Release" .Release) }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-encryption-key-secondary
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: "{{- include "chart.secretValue" (dict "secretName" (print (include "chart.fullname" .) "-encryption-key") "key" "NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY" "defaultValue" (randAlphaNum 36) "Release" .Release) }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-db-url
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    checksum/postgres-password: {{ include "chart.secretValue" (dict "secretName" "postgresql" "key" "postgres-password" "defaultValue" (randAlphaNum 32) "Release" .Release) | sha256sum }}
type: Opaque
stringData:
  url: |
    postgresql://{{ .Values.postgresql.auth.username }}:{{ include "chart.secretValue" (dict "secretName" "postgresql" "key" "postgres-password" "defaultValue" (randAlphaNum 32) "Release" .Release) | b64dec }}@{{ .Values.postgresql.auth.host }}:{{ .Values.postgresql.auth.port }}/{{ .Values.postgresql.auth.database }}
---