name: Build Emporium Apps

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/vscode/build/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'charts/vscode/build/**'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          
      - name: Extract CODE_SERVER_VERSION from Dockerfile
        id: extract_version
        run: |
          VERSION=$(grep 'ENV CODE_SERVER_VERSION' ./charts/vscode/build/Dockerfile | awk -F"=" '{print $2}')
          echo "::set-output name=version::$VERSION"
  
      - name: Build and push vscode
        uses: docker/build-push-action@v5
        with:
          file: ./charts/vscode/build/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ vars.CONTAINER_REGISTRY }}/vscode:${{ steps.extract_version.outputs.version }}