apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WORKSPACE_DIR
              value: "{{ .Values.env.WORKSPACE_DIR }}"
            - name: METRICS_JSON_PATH
              value: "{{ .Values.env.METRICS_JSON_PATH }}"
            - name: HOST
              value: "{{ .Values.env.HOST }}"
            - name: WORKSPACE_DELETE_EXPIRED
              value: "{{ .Values.env.WORKSPACE_DELETE_EXPIRED }}"
            - name: WORKSPACE_EXPIRE_DAYS
              value: "{{ .Values.env.WORKSPACE_EXPIRE_DAYS }}"
            - name: CHROME_REFRESH_TIME
              value: "{{ .Values.env.CHROME_REFRESH_TIME }}"
            - name: MAX_CONCURRENT_SESSIONS
              value: "{{ .Values.env.MAX_CONCURRENT_SESSIONS }}"
            - name: MAX_QUEUE_LENGTH
              value: "{{ .Values.env.MAX_QUEUE_LENGTH }}"
            - name: CONNECTION_TIMEOUT
              value: "{{ .Values.env.CONNECTION_TIMEOUT }}"
            - name: DEFAULT_BLOCK_ADS
              value: "{{ .Values.env.DEFAULT_BLOCK_ADS }}"
            - name: DEFAULT_HEADLESS
              value: "{{ .Values.env.DEFAULT_HEADLESS }}"
            - name: DEFAULT_IGNORE_HTTPS_ERRORS
              value: "{{ .Values.env.DEFAULT_IGNORE_HTTPS_ERRORS }}"
            - name: DEFAULT_IGNORE_DEFAULT_ARGS
              value: "{{ .Values.env.DEFAULT_IGNORE_DEFAULT_ARGS }}"
            - name: ENABLE_API_GET
              value: "{{ .Values.env.ENABLE_API_GET }}"
            - name: FUNCTION_ENABLE_INCOGNITO_MODE
              value: "{{ .Values.env.FUNCTION_ENABLE_INCOGNITO_MODE }}"
            - name: EXIT_ON_HEALTH_FAILURE
              value: "{{ .Values.env.EXIT_ON_HEALTH_FAILURE }}"
            - name: DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR
              value: "{{ .Values.env.DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR }}"
            - name: ENABLE_DEBUGGER
              value: "{{ .Values.env.ENABLE_DEBUGGER }}"
            - name: ENABLE_CORS
              value: "{{ .Values.env.ENABLE_CORS }}"
            - name: ENABLE_XVBF
              value: "{{ .Values.env.ENABLE_XVBF }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
